export const teamData = [
  {
    id: 1,
    image: "",
    fname: "Marvin",
    lname: "Manzi",
    desc: "What you see is what you get, Presentation is key!",
  },
  {
    id: 2,
    image: "",
    fname: "Vanessa",
    lname: "Umutoni",
    desc: "It’s never about just developing software applications but about creating impactful/ valuable solutions for our societies. Society is our motivation.",
  },
  {
    id: 3,
    image: "",
    fname: "Fiacre",
    lname: "Rugwizangoga",
    desc: "First impressions are hard to change therefore we focus on making our products user-friendly at first use. “Simplicity + quality always makes a difference",
  },
  {
    id: 4,
    image: "",
    fname: "Didier",
    lname: "Zigama",
    desc: "It’s not about how many languages I can code, but how many good solutions I can provide. The user does not need to know all the complications in the back-end that’s why our solutions must be simple to use and understand.",
  },
  {
    id: 5,
    image: "",
    fname: "Allian",
    lname: "Kanjangwe",
    desc: "Nothing inspires like solving a larger problem with simple but powerful solutions! Working with PIVOT ACCESS has helped me to build solutions that I know will impact thousands of lives.",
  },
  {
    id: 6,
    image: "",
    fname: "Peter",
    lname: "Fourier",
    desc: "We make things happen and that’s because every employee is unique. Each product is a combina- tion of hardworking programmers, developers, designers, testers and analysts who take each milestone as a final project itself.",
  },
  {
    id: 7,
    image: "",
    fname: "Donatien",
    lname: "Masengesho",
    desc: "We are avid students for life, every new challenge is a new opportunity to be innovative and provides us a platform to learn and develop our skills.",
  },
  {
    id: 8,
    image: "",
    fname: "Yonah",
    lname: "Gasa-Gara",
    desc: "My time at Pivot has been a true learning experience. Everything we produce is a product of teamwork and dedication. I’m glad to be able to work with such inspiring colleagues.",
  },
  {
    id: 9,
    image: "",
    fname: "Merab",
    lname: "Twahirwa",
    desc: "Building solutions that give our clients a great and unforgettable experience is what keeps us at the forefront in what we do.",
  },
  {
    id: 10,
    image: "",
    fname: "Maurice",
    lname: "Kagame",
    desc: "The philosophy of putting customers first has enriched the quality of products we offer at PIVOT ACCESS,",
  },
  {
    id: 11,
    image: "",
    fname: "Christain",
    lname: "Mutesa",
    desc: "At PIVOT ACCESS we work with our customers to provide relevant services to their customers in the simplest form possible. Simple is powerful!",
  },
  {
    id: 12,
    image: "",
    fname: "Sildio",
    lname: "Mbonyumuhire",
    desc: "My experience at Pivot Access has given me not only the ability to solve complex problems but also the ability to quickly understand clients' aspirations, goals and needs",
  },
  {
    id: 13,
    image: "",
    fname: "Joseph",
    lname: "Karangwa",
    desc: "The ability to work on your own initiative and remain motivated, is the key success factor in everything you do. Be everywhere, do everything and never fail to satisfy a customer!",
  },
  {
    id: 14,
    image: "",
    fname: "Patient",
    lname: "Baraka",
    desc: "Write enough code, have fun with it!",
  },
  {
    id: 15,
    image: "",
    fname: "Elodie",
    lname: "Ndayikunda",
    desc: "We focus on the ideas that are practical, those that give everybody's life meaning",
  },
  {
    id: 16,
    image: "",
    fname: "Vivens",
    lname: "Mutangana",
    desc: "I manage and improve internal security of software during and after software development life cycle",
  },
];
